version: 2
jobs:
  build:
    docker:
      - image: node:7
        environment:
          - DEPLOY_BRANCH=master
          - STAGING_BRANCH=develop
          - DOCKER_SRC_IMAGE=ram-id
          - DOCKER_REPOSITORY=wbtransport/ram-id
          - DOCKER_USERNAME=danielfdsilva
          # DOCKER_PASSWD = Set through the interface

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              npm run all
            else
              echo "Skip building site"
            fi

      - add_ssh_keys:
          fingerprints:
            - "e0:8c:34:e7:1a:c5:13:b6:fc:b6:25:a0:cc:10:98:49"

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Deploy to Docker hub
          command: /bin/bash ./.circleci/deploy-docker.sh

      - run:
          name: Deploy to GH Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              cd dist
              git init
              git config user.name "Devseed-CI"
              git config user.email "dev@developmentseed.org"
              git add .
              git commit -m "CI deploy [skip ci]"
              git remote add origin git@github.com:WorldBank-Transport/ram-iD.git
              git push origin --force --quiet HEAD:gh-pages
              rm -rf .git
            else
              echo "Skip deploying to Github"
            fi
