version: 2
jobs:
  build:
    docker:
      - image: node:7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run all
            else
              echo "Skip building site"
            fi

      - add_ssh_keys:
          fingerprints:
            - "e0:8c:34:e7:1a:c5:13:b6:fc:b6:25:a0:cc:10:98:49"

      - run:
          name: Deploy to GH Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd build
              git init
              git config user.name "Devseed-CI"
              git config user.email "dev@developmentseed.org"
              git add .
              git commit -m "CI deploy [skip ci]"
              git remote add origin git@github.com:Worldbank-Transport/ram-iD.git
              git push origin --force --quiet HEAD:gh-pages
              rm -rf .git
            else
              echo "Skip deploying to Github"
            fi
